# Generated by Django 6.0.2 on 2026-02-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='matricule_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='prenom',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='tuteur_nom',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
