# Generated by Django 6.0.2 on 2026-02-10 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
        ('students', '0002_alter_etudiant_matricule_id_alter_etudiant_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='annee_academique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='references.anneeacademique'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='references.filiere'),
        ),
    ]
