# Generated by Django 6.0.2 on 2026-02-10 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
        ('students', '0003_etudiant_annee_academique_etudiant_filiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='matricule_id',
            field=models.CharField(blank=True, db_index=True, max_length=25, unique=True),
        ),
        migrations.CreateModel(
            name='EtudiantParAnnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.anneeacademique')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to='students.etudiant')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.filiere')),
            ],
            options={
                'verbose_name': 'Scolarité Étudiant',
                'unique_together': {('etudiant', 'annee_academique')},
            },
        ),
    ]
