# Generated by Django 6.0.2 on 2026-02-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquefiliere',
            name='actif',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
