# Generated by Django 6.0.2 on 2026-02-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StagingInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_brut', models.CharField(max_length=100)),
                ('prenom_brut', models.CharField(max_length=100)),
                ('telephone_brut', models.CharField(max_length=20)),
                ('tuteur_brut', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('DOUBLON', 'Doublon suspect')], default='EN_ATTENTE', max_length=20)),
                ('score_doublon', models.FloatField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
